#!/bin/bash
##Example script for ALAIS
BOOL_AUTOINST=TRUE #Enables this script
KEYMAP=uk
EDITOR=nano
DEVICE=/dev/sda
LTS=TRUE #LTS Linux Kernel (if you have issues with x-org & virutalbox video drivers for example)
language=en_GB
timezone=Europe/London
hwclockvar=UTC
hostname=arch
networkman=networkmanager
password=root
BOOL_BASICSETUP=FALSE
BOOL_SSH=FALSE
BOOL_NFS=FALSE
BOOL_SAMBA=FALSE
BOOL_READAHEAD=FALSE
BOOL_FONTCONFIG=NORM #Will change to nonbool
BOOL_XORG=FALSE
BOOL_CUPS=FALSE
DESKTOP_ENV= #No window manager/destop environment because no xorg
DISPLAY_MAN= #No display manager because no xorg
BOOL_PAMAC=FALSE    #No pamac or octopi because there is no xorg/wm/de
BOOL_OCTOPI=FALSE
BOOL_PLYMOUTH=FALSE
CUSTOMPKGS= #No custompackages required
AURCUSTOMPKGS=
partitioner=parted
echo Auto-Script Loaded Sucessfully!
