#!/bin/bash
BOOL_AUTOINST=FALSE
if [[ -f `pwd`/autoinstall ]]; then
    source `pwd`/autoinstall
else
    echo An error occured: not autoinstall file provided
    read
    exit 1
fi
ARCHI=`uname -m` #ARCHItecture

useradd -m -G wheel -s /bin/bash $user
passwd $user <<EOF
$password
$password
EOF
set -i '/%wheel ALL=(ALL) ALL/s/^#//' /etc/sudoers
TEMPADDEDTOPOSTINST=
TEMPADDEDAUR=
BOOL_UBUNTUCONF=FALSE
if [[ $BOOL_BASICSETUP == TRUE ]]; then TEMPADDEDTOPOSTINST=$TEMPADDEDTOPOSTINST bc rsync mlocate bash-completion pkgstats ntp zip unzip unrar p7zip lzop cpio avahi nss-mdns alsa-utils alsa-plugins pulseaudio pulseaudio-alsa ntfs-3g dosfstools exfat-utils f2fs-tools fuse fuse-exfat autofs; fi
if [[ $BOOL_BASICSETUP == TRUE ]] && [[ $ARCH == x86_64 ]]; then TEMPADDEDTOPOSTINST=$TEMPADDEDTOPOSTINST lib32-alsa-plugins lib32-libpulse; fi
if [[ $BOOL_SSH == TRUE ]]; then TEMPADDEDTOPOSTINST=$TEMPADDEDTOPOSTINST openssh; fi
if [[ $BOOL_NFS == TRUE ]]; then TEMPADDEDTOPOSTINST=$TEMPADDEDTOPOSTINST nfs-utils; fi
if [[ $BOOL_SAMBA == TRUE ]]; then TEMPADDEDTOPOSTINST=$TEMPADDEDTOPOSTINST samba smbnetfs; fi
if [[ $FONTCONFIG == NORM ]]; then TEMPADDEDTOPOSTINST=$TEMPADDEDTOPOSTINST cairo fontconfig freetype2; fi
if [[ $FONTCONFIG == INF ]]; then TEMPADDEDTOPOSTINST=$TEMPADDEDTOPOSTINST infinality-bundle
if [[ $FONTCONFIG == INF ]] && [[ $ARCH == x86_64 ]]; then TEMPADDEDTOPOSTINST=$TEMPADDEDTOPOSTINST infinality-bundle-multilib; fi
if [[ $FONTCONFIG == UBUNTU ]]; then BOOL_UBUNTUCONF=TRUE; fi
if [[ $BOOL_XORG == TRUE ]]; then
    TEMPADDEDTOPOSTINST=$TEMPADDEDTOPOSTINST xorg-server xorg-server-utils xorg-server-xwayland xorg-xinit xorg-xkill xf86-input-synaptics xf86-input-mouse xf86-input-keyboard xf86-input-wacom xf86-input-libinput mesa
    _vga=`lspci | grep VGA | tr "[:upper:]" "[:lower:]"`
    _vga_length=`lspci | grep VGA | wc -l`
    pacman --noconfirm -S dmidecode
    if [[ -n $(dmidecode --type 1 | grep VirtualBox) ]]; then
    #VBOX
    pacman --noconfirm -S virtualbox-guest-utils mesa-libgl virtualbox-guest-dkms
    
    elif [[ $_vga_length -eq 2 ]] && [[ -n $(echo ${_vga} | grep "nvidia") || -f /sys/kernel/debug/dri/0/vbios.rom ]]; then
    #NVidia bumblebee
    pacman --noconfirm -S --needed xf86-video-intel bumblebee nvidia
    
    elif [[ -n $(echo ${_vga} | grep "nvidia") || -f /sys/kernel/debug/dri/0/vbios.rom ]]; then
    #Nvidia
    pacman --noconfirm -S --needed nvidia nvidia-utils
    elif [[ -n $(echo ${_vga} | grep "advanced micro devices" || -f /sys/kernel/debug/dri/0/radeon_pm_info || -f /sys/kernel/debug/dri/0/radeon_sa_info ]]; then
    #AMD/ATI
    elif [[ -n $(echo ${_vga} | grep "intel corporation") || -f /sys/kernel/debug/dri/0/i915_capabilities ]]; then
    #Intel
    else
    #VESA
    fi
    
fi
